production:
   solr:
     hostname: ec2-54-225-101-202.compute-1.amazonaws.com
     port: 5432
     log_level: WARNING
     path: /solr/production
      read_timeout: 2
      open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
